# Generated by Django 4.0.5 on 2022-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('M', 'Moderation'), ('P', 'Published'), ('R', 'Rejected')], max_length=1),
        ),
    ]
