# Generated by Django 4.0.5 on 2022-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('M', 'Moderation'), ('P', 'Published'), ('R', 'Rejected!')], max_length=1),
        ),
    ]
