# Generated by Django 4.0.5 on 2022-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('M', 'Moderation'), ('P', 'Published'), ('R', 'Rejected')], default='M', max_length=1),
        ),
    ]
