# Generated by Django 4.0.5 on 2022-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cr', 'Created'), ('de', 'Delivered'), ('pr', 'Processed'), ('ca', 'Cancelled')], default='cr', max_length=2),
        ),
    ]
